In [4]:
import pandas as pd
import sys
from pathlib import Path

# Path to the folder containing your gene_harmony package
BASE_DIR = Path("/Users/rsaxs014/Desktop/gene-harmony/src")
sys.path.insert(0, str(BASE_DIR))

from gene_harmony import GeneHarmony

In [5]:
# Define data directory
DATA_DIR = Path("/Users/rsaxs014/Desktop/gene-harmony/src/gene_harmony/data")

# List of (dict key, filename) pairs
files = [
    ("primary_df", "summary_df.h5"),
    ("ortholog_df", "ortholog_match_subset_genes_df.h5"),
    ("flj_clone_df", "flj_clone_symbol_match_subset_genes_df.h5"),
    ("disease_df", "disease_prefix_match_subset_genes_df.h5"),
    ("hgnc_gene_group_df", "gene_group_prefix_match_subset_genes_df.h5"),
    ("gene_id_df", "gene_id_match_subset_genes_df.h5"),
    ("mgi_withdrawn_df", "mgi_withdrawn_symbol_match_subset_genes_df.h5"),
    ("ncbi_gene_group_df", "ncbi_gene_group_symbol_match_subset_genes_df.h5"),
    ("ncbi_gene_interaction_df", "ncbi_gene_interaction_symbol_match_subset_genes_df.h5"),
    ("ncbi_gene_neighbor_df", "ncbi_gene_neighbor_match_subset_genes_df.h5"),
    ("placeholder_df", "placeholder_match_subset_genes_df.h5"),
    ("previous_df", "previous_symbol_match_subset_genes_df.h5"),
    ("protein_mass_df", "protein_mass_match_subset_genes_df.h5"),
]

# Load all DataFrames into a dictionary
dfs = {key: pd.read_hdf(DATA_DIR / filename, key='df') for key, filename in files}

# Create the resolver
gh = GeneHarmony(**dfs)

In [6]:
# search primary dataframe
rows_primary = gh.resolve(symbol ="KRAS")
rows_primary

,HGNC_ID,ENSG_ID,NCBI_ID,primary_gene_symbol,gene_symbol,captured,captured as:
53678,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,'C-K-RAS,F,None
53679,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,C-K-RAS,F,None
53680,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,CFC2,T,Prefix Condition Symbol
53681,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS2A,F,None
53682,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS2B,F,None
53683,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS4A,F,None
53684,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS4B,F,None
53685,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-Ras,F,None
53686,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-Ras 2,F,None
53687,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-Ras4B,F,None
53688,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KI-RAS,F,None
53689,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KRAS,T,Primary Gene Symbol
53690,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KRAS1,F,None
53691,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KRAS2,T,"Previous Symbol, Withdrawn MGI Symbol"
53692,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,NS,F,None
53693,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,NS3,T,Prefix Condition Symbol
53694,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,OES,T,Prefix Condition Symbol
53695,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,RALD,T,Prefix Condition Symbol
53696,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,RASK2,T,Prefix Gene Group Symbol
53697,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,c-Ki-ras,F,None
53698,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,c-Ki-ras2,F,None
81133,{HGNC:7989},{ENSG00000213281},{GENE ID:4893},NRAS,KRAS,T,Ortholog Symbol

In [7]:
rows_primary = gh.resolve(symbol ="KRAS", match_type= "partial")
rows_primary

,HGNC_ID,ENSG_ID,NCBI_ID,primary_gene_symbol,gene_symbol,captured,captured as:
53678,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,'C-K-RAS,F,None
53679,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,C-K-RAS,F,None
53680,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,CFC2,T,Prefix Condition Symbol
53681,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS2A,F,None
53682,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS2B,F,None
53683,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS4A,F,None
53684,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-RAS4B,F,None
53685,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-Ras,F,None
53686,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-Ras 2,F,None
53687,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,K-Ras4B,F,None
53688,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KI-RAS,F,None
53689,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KRAS,T,Primary Gene Symbol
53690,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KRAS1,F,None
53691,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,KRAS2,T,"Previous Symbol, Withdrawn MGI Symbol"
53692,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,NS,F,None
53693,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,NS3,T,Prefix Condition Symbol
53694,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,OES,T,Prefix Condition Symbol
53695,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,RALD,T,Prefix Condition Symbol
53696,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,RASK2,T,Prefix Gene Group Symbol
53697,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,c-Ki-ras,F,None
53698,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},KRAS,c-Ki-ras2,F,None
53699,{HGNC:6406},{ENSG00000220635},{GENE ID:3844},KRASP1,KRAS1P,T,Previous Symbol
53700,{HGNC:6406},{ENSG00000220635},{GENE ID:3844},KRASP1,KRASP1,T,Primary Gene Symbol
53701,{HGNC:6406},{},{GENE ID:3844},KRASP1,c-Kras1,F,None
77847,{HGNC:25121},{ENSG00000270170},{GENE ID:152217},NCBP2AS2,KRASIM,F,None
81133,{HGNC:7989},{ENSG00000213281},{GENE ID:4893},NRAS,KRAS,T,Ortholog Symbol

In [ ]:
gh.resolve(symbol="KRAS", source="Prefix Condition Symbol")

,primary_gene_symbol,alias_symbol,HGNC_ID,ENSG_ID,NCBI_ID,Prefix Disease Symbol Match,Matching Phenotype Symbol
46106,KRAS,CFC2,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},True,CFC2
46118,KRAS,NS3,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},True,NS3
46119,KRAS,OES,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},True,OES
46120,KRAS,RALD,{HGNC:6407},{ENSG00000133703},{GENE ID:3845},True,RALD