In [1]:
from pathlib import Path

import pandas as pd

from gene_jar import GeneJar, MatchType

In [2]:
# Define data directory
DATA_DIR = Path("/Users/rsaxs014/Desktop/gene-jar/src/gene_jar/data")

# List of (dict key, filename) pairs
files = [
    ("primary_df", "summary_df.h5"),
    ("ortholog_df", "ortholog_match_subset_genes_df.h5"),
    ("flj_clone_df", "flj_clone_symbol_match_subset_genes_df.h5"),
    ("phenotype_df", "phenotype_match_subset_genes_df.h5"),
    ("hgnc_gene_group_df", "gene_group_prefix_match_subset_genes_df.h5"),
    ("gene_id_df", "gene_id_match_subset_genes_df.h5"),
    ("mgi_withdrawn_df", "mgi_withdrawn_symbol_match_subset_genes_df.h5"),
    ("ncbi_related_gene_df", "ncbi_related_gene_match_subset_genes_df.h5"),
    (
        "ncbi_gene_interaction_df",
        "ncbi_gene_interaction_symbol_match_subset_genes_df.h5",
    ),
    ("ncbi_gene_neighbor_df", "ncbi_gene_neighbor_match_subset_genes_df.h5"),
    ("placeholder_df", "placeholder_match_subset_genes_df.h5"),
    ("previous_df", "previous_symbol_match_subset_genes_df.h5"),
    ("protein_mass_df", "protein_mass_match_subset_genes_df.h5"),
    ("alternate_abbreviation_df", "alt_abbrev_symbol_match_subset_genes_df.h5"),
]

# Load all DataFrames into a dictionary
dfs = {key: pd.read_hdf(DATA_DIR / filename, key="df") for key, filename in files}

# Create the resolver
gj = GeneJar(**dfs)

In [3]:
gj.resolve("KRAS")

,candidate_rank,primary_gene_symbol,HGNC_ID,NCBI_ID,ENSG_ID,best_category,qualifier,matched_symbol,matched_categories,relationship_count
0,1,KRAS,{HGNC:6407},{GENE ID:3845},{ENSG00000133703},Primary Gene Symbol,{},{KRAS},[Primary Gene Symbol],1
1,2,NRAS,{HGNC:7989},{GENE ID:4893},{ENSG00000213281},Ortholog Symbol,{'Matching Species': ['Norway rat - BN/NHsdMcw...,{KRAS},[Ortholog Symbol],1

In [4]:
rows_primary = gj.resolve(symbol="KRAS", match_type=MatchType.PARTIAL)
rows_primary

,candidate_rank,primary_gene_symbol,HGNC_ID,NCBI_ID,ENSG_ID,best_category,qualifier,matched_symbol,matched_categories,relationship_count
0,1,KRAS,"{HGNC:6407, {'HGNC:6407'}}","{{'GENE ID:3845'}, GENE ID:3845}","{ENSG00000133703, {'ENSG00000133703'}}",Primary Gene Symbol,{},"{KRAS, KRAS2}","[Primary Gene Symbol, Previous Symbol, Alterna...",4
1,2,KRASP1,"{HGNC:6406, {'HGNC:6406'}}","{{'GENE ID:3844'}, GENE ID:3844}","{ENSG00000220635, {'ENSG00000220635'}, set()}",Primary Gene Symbol,{},"{KRAS1P, KRASP1, c-Kras1}","[Primary Gene Symbol, Previous Symbol, Alterna...",3
2,3,NRAS,{HGNC:7989},{GENE ID:4893},{ENSG00000213281},Ortholog Symbol,{'Matching Species': ['Norway rat - BN/NHsdMcw...,{KRAS},[Ortholog Symbol],1

In [6]:
gj.resolve("ABL")

,candidate_rank,primary_gene_symbol,HGNC_ID,NCBI_ID,ENSG_ID,best_category,qualifier,matched_symbol,matched_categories,relationship_count
0,1,ABL1,{HGNC:76},{GENE ID:25},{ENSG00000097007},Previous Symbol,{'Previous Symbol Source': 'HGNC'},{ABL},"[Previous Symbol, Gene Group Symbol]",2
1,2,MTTP,{HGNC:7467},{GENE ID:4547},{ENSG00000138823},Phenotype Symbol,{'Matching Phenotype Symbol': 'ABL'},{ABL},[Phenotype Symbol],1

In [7]:
result = gj.ambiguity_check("ABL")

result.is_ambiguous

True

In [8]:
result

AmbiguityResult(is_ambiguous=True, gene_matches=[GeneMatch(primary_gene_symbol='ABL1', hgnc_id={'HGNC:76'}, ncbi_id={'GENE ID:25'}, ensg_id={'ENSG00000097007'}), GeneMatch(primary_gene_symbol='MTTP', hgnc_id={'HGNC:7467'}, ncbi_id={'GENE ID:4547'}, ensg_id={'ENSG00000138823'})])

In [9]:
result.gene_matches

[GeneMatch(primary_gene_symbol='ABL1', hgnc_id={'HGNC:76'}, ncbi_id={'GENE ID:25'}, ensg_id={'ENSG00000097007'}),
 GeneMatch(primary_gene_symbol='MTTP', hgnc_id={'HGNC:7467'}, ncbi_id={'GENE ID:4547'}, ensg_id={'ENSG00000138823'})]

In [10]:
result.gene_matches[0].primary_gene_symbol

'ABL1'

In [11]:
result.gene_matches[0].hgnc_id

{'HGNC:76'}

In [12]:
result.gene_matches[0].ncbi_id

{'GENE ID:25'}

In [13]:
result.gene_matches[0].ensg_id

{'ENSG00000097007'}